package br.com.cidadesinteligentes.modules.alvaraconstrucaocivil.requerimentoalvaraconstrucao.repository;

import br.com.cidadesinteligentes.modules.alvaraconstrucaocivil.requerimentoalvaraconstrucao.model.ConstructionLicenseRequirement;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
/**
 * Data access repository for the {@link ConstructionLicenseRequirement} entity.
 * Provides CRUD operations and database interaction methods 
 * for construction license requirements.
 *
 * This repository is responsible for persisting and retrieving 
 * construction-related requirement records, 
 * including their associations with documents and technical responsibles.
 *
 * Author: Caio Alves
 */

@Repository
public interface IConstructionLicenseRequirementRepository extends JpaRepository<ConstructionLicenseRequirement, Long>{

    List<ConstructionLicenseRequirement> findByTechnicalResponsibleId(UUID technicalResponsibleId);

  List<ConstructionLicenseRequirement> findByTechnicalResponsibleRegistrationId(String registrationId);

  /**
   * Finds a paginated list of ConstructionLicenseRequirements whose associated RequirementType matches the specified name.
   * The query is automatically generated by Spring Data JPA based on the method name, traversing the relationship.
   *
   * @param typeName The name of the RequirementType to filter by.
   * @param pageable Pagination and sorting information.
   * @return A Page containing the ConstructionLicenseRequirements matching the type name.
   * @author Caio Alves
   */
  Page<ConstructionLicenseRequirement> findByRequirementTypeName(String typeName, Pageable pageable);

    Optional<ConstructionLicenseRequirement> findFirstByOrderByIdDesc();
}
