package br.com.cidadesinteligentes.modules.solicitacaoservicomunicipal.solicitacao.repository;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import br.com.cidadesinteligentes.modules.solicitacaoservicomunicipal.solicitacao.model.Request;

/**
 * Data access repository for the {@link Request} entity.
 * Provides CRUD operations and database interaction methods for service requests.
 *
 * @author Caio Alves, Giovane Neves
 */

@Repository
public interface IRequestRepository extends JpaRepository<Request, UUID>{

    @Query("SELECT r FROM Request r WHERE r.profile.id = :profileId")
    Page<Request> findAllByProfileId(@Param("profileId") UUID profileId, Pageable pageable);

    /**
     * Finds a paginated list of Requests that match the specified type.
     * The query is automatically generated by Spring Data JPA based on the method name.
     *
     * @param type The type of the Request to filter by.
     * @param pageable Pagination and sorting information.
     * @return A Page containing the Requests matching the type, respecting pagination settings.
     * @author Caio Alves
     */
    Page<Request> findByType(String type, Pageable pageable);

    /**
     * Retrieves a paginated list of Requests filtered by the new status recorded in the StatusHistory.
     * The query navigates the one-to-one relationship to the StatusHistory entity.
     *
     * @param statusHistoryNewStatus The new status to filter requests by.
     * @param pageable Pagination and sorting information.
     * @return A Page containing Requests matching the status.
     */
    Page<Request> findAllByStatusHistory_NewStatus(String statusHistoryNewStatus, Pageable pageable);

    /**
     * Retrieves a paginated list of Requests filtered by a list of statuses (newStatus) recorded in the StatusHistory.
     *
     * @param statuses The list of target statuses (e.g., ["COMPLETE", "REJECTED"]).
     * @param pageable Pagination and sorting information.
     * @return A Page containing Requests matching any of the provided statuses.
     */
    Page<Request> findAllByStatusHistory_NewStatusIn(List<String> statuses, Pageable pageable);

    /**
     * Retrieves the first Request associated with the given Municipal Service ID,
     * ordered by creation date in descending order.
     * <p>
     * This is typically used to find the most recently created Request linked to a service.
     * @param servicoMunicipalId The ID of the Municipal Service.
     * @return An Optional containing the most recent Request found.
     */
    Optional<Request> findFirstByServicoMunicipalIdOrderByCreatedAtDesc(Long servicoMunicipalId);

    /**
     * Finds a Request entity by its unique protocol number.
     *
     * @param protocolNumber The protocol number of the Request.
     * @return An Optional containing the Request found.
     */
    Optional<Request> findByProtocolNumber(String protocolNumber);

    List<Request> findAllByServicoMunicipalId(Long servicoMunicipalId);

}
